### ISSUE TITLE
some question about uav_simulator

### ISSUE THREAD

**Issue by Mealoore** [ZJU-FAST-Lab/ego-planner#43]
When using your so3 simulator, I publish the command
```
header: 
  seq: 21
  stamp: 
    secs: 0
    nsecs:         0
  frame_id: ''
position: 
  x: nan
  y: nan
  z: nan
velocity: 
  x: 0.0
  y: 0.0
  z: 0.0
acceleration: 
  x: 0.0
  y: 0.0
  z: 0.0
yaw: 2.0
yaw_dot: 0.0
kx: [0.0, 0.0, 0.0]
kv: [0.0, 0.0, 0.0]
trajectory_id: 0
trajectory_flag: 0
```
the height of uav is not correct, I think it should be at original point
